openapi: 3.0.1
info:
  title: order-management
  version: "1.0"
paths:
  /customer:
    get:
      tags:
      - Customers
      operationId: getCustomers
      responses:
        "200":
          description: getCustomers 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Customer"
    post:
      tags:
      - Customers
      operationId: createCustomer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerCreateDTO"
        required: true
      responses:
        "200":
          description: createCustomer 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
  /customer/{id}:
    get:
      tags:
      - Customers
      operationId: getCustomer
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: getCustomer 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
    put:
      tags:
      - Customers
      operationId: updateCustomer
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerUpdateDTO"
        required: true
      responses:
        "200":
          description: updateCustomer 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
    delete:
      tags:
      - Customers
      operationId: deleteCustomer
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: deleteCustomer 200 response
  /orders:
    get:
      tags:
      - Orders
      operationId: getOrders
      responses:
        "200":
          description: getOrders 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
    post:
      tags:
      - Orders
      operationId: createOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderCreateDTO"
        required: true
      responses:
        "200":
          description: createOrder 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
  /orders/{id}:
    get:
      tags:
      - Orders
      operationId: getOrder
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: getOrder 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
    post:
      tags:
      - Orders
      operationId: updateOrder
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderUpdateDTO"
        required: true
      responses:
        "200":
          description: updateOrder 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
    delete:
      tags:
      - Orders
      operationId: deleteOrder
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: deleteOrder 200 response
components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: integer
          format: int64
          nullable: true
        email:
          type: string
        firstName:
          type: string
        familyName:
          type: string
    CustomerCreateDTO:
      type: object
      properties:
        email:
          type: string
        firstName:
          type: string
        familyName:
          type: string
    CustomerUpdateDTO:
      type: object
      properties:
        firstName:
          type: string
        familyName:
          type: string
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
          nullable: true
        dateCreated:
          type: string
          format: date
        address:
          type: string
        paid:
          type: boolean
        delivered:
          type: boolean
        totalAmount:
          type: number
        customer:
          nullable: true
          allOf:
          - $ref: "#/components/schemas/Customer"
        orderItems:
          type: array
          items:
            $ref: "#/components/schemas/OrderItem"
    OrderCreateDTO:
      type: object
      properties:
        address:
          type: string
        customerId:
          type: integer
          format: int64
        productQuantities:
          type: object
          additionalProperties:
            type: integer
            format: int64
    OrderItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
          nullable: true
        productId:
          type: integer
          format: int64
        quantity:
          minimum: 1
          type: integer
          format: int64
        unitPrice:
          type: number
    OrderUpdateDTO:
      type: object
      properties:
        paid:
          type: boolean
        delivered:
          type: boolean
